/*
 * generated by Xtext 2.23.0
 */
package org.example.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.PantryTextualRuntimeModule;
import org.example.PantryTextualStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PantryTextualIdeSetup extends PantryTextualStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PantryTextualRuntimeModule(), new PantryTextualIdeModule()));
	}
	
}
