/*
 * generated by Xtext 2.23.0
 */
package org.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PantryTextualUiModule extends AbstractPantryTextualUiModule {

	public PantryTextualUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
