/*
 * generated by Xtext 2.23.0
 */
package org.textual.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.textual.parser.antlr.internal.InternalRecipeMLParser;
import org.textual.services.RecipeMLGrammarAccess;

public class RecipeMLParser extends AbstractAntlrParser {

	@Inject
	private RecipeMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRecipeMLParser createParser(XtextTokenStream stream) {
		return new InternalRecipeMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Recipe";
	}

	public RecipeMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RecipeMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
