/*
 * generated by Xtext 2.23.0
 */
package org.textual.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.textual.RecipeMLRuntimeModule;
import org.textual.RecipeMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RecipeMLIdeSetup extends RecipeMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RecipeMLRuntimeModule(), new RecipeMLIdeModule()));
	}
	
}
