/*
 * generated by Xtext 2.23.0
 */
package org.textual.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RecipeMLUiModule extends AbstractRecipeMLUiModule {

	public RecipeMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
