/*
 * generated by Xtext 2.23.0
 */
package org.textual.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRecipeMLScopeProvider extends DelegatingScopeProvider {
}
