/*
 * generated by Xtext 2.23.0
 */
package org.textual.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import recipeMLTextual.ui.internal.RecipeMLTextualActivator;

public class RecipeMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RecipeMLTextualActivator.getInstance().getInjector("org.textual.RecipeML");
	}

}
