/*
 * generated by Xtext 2.23.0
 */
package org.example.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.example.parser.antlr.internal.InternalPantryTextualParser;
import org.example.services.PantryTextualGrammarAccess;

public class PantryTextualParser extends AbstractAntlrParser {

	@Inject
	private PantryTextualGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPantryTextualParser createParser(XtextTokenStream stream) {
		return new InternalPantryTextualParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Pantry";
	}

	public PantryTextualGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PantryTextualGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
