/*
 * generated by Xtext 2.23.0
 */
package org.example.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.example.ide.contentassist.antlr.internal.InternalPantryTextualParser;
import org.example.services.PantryTextualGrammarAccess;

public class PantryTextualParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(PantryTextualGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, PantryTextualGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
			builder.put(grammarAccess.getPantryAccess().getGroup(), "rule__Pantry__Group__0");
			builder.put(grammarAccess.getPantryAccess().getGroup_2(), "rule__Pantry__Group_2__0");
			builder.put(grammarAccess.getIngredientAccess().getGroup(), "rule__Ingredient__Group__0");
			builder.put(grammarAccess.getIngredientAccess().getGroup_2(), "rule__Ingredient__Group_2__0");
			builder.put(grammarAccess.getMassAccess().getGroup(), "rule__Mass__Group__0");
			builder.put(grammarAccess.getMassAccess().getGroup_2(), "rule__Mass__Group_2__0");
			builder.put(grammarAccess.getMassAccess().getGroup_3(), "rule__Mass__Group_3__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
			builder.put(grammarAccess.getPantryAccess().getIngredientAssignment_1(), "rule__Pantry__IngredientAssignment_1");
			builder.put(grammarAccess.getPantryAccess().getIngredientAssignment_2_1(), "rule__Pantry__IngredientAssignment_2_1");
			builder.put(grammarAccess.getIngredientAccess().getNameAssignment_1(), "rule__Ingredient__NameAssignment_1");
			builder.put(grammarAccess.getIngredientAccess().getMassAssignment_2_1(), "rule__Ingredient__MassAssignment_2_1");
			builder.put(grammarAccess.getMassAccess().getAmountAssignment_2_1(), "rule__Mass__AmountAssignment_2_1");
			builder.put(grammarAccess.getMassAccess().getUnitAssignment_3_1(), "rule__Mass__UnitAssignment_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private PantryTextualGrammarAccess grammarAccess;

	@Override
	protected InternalPantryTextualParser createParser() {
		InternalPantryTextualParser result = new InternalPantryTextualParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PantryTextualGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PantryTextualGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
