/*
 * generated by Xtext 2.23.0
 */
package org.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPantryTextualScopeProvider extends DelegatingScopeProvider {
}
