/*
 * generated by Xtext 2.23.0
 */
package org.example;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PantryTextualStandaloneSetup extends PantryTextualStandaloneSetupGenerated {

	public static void doSetup() {
		new PantryTextualStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
