/*
 * generated by Xtext 2.23.0
 */
package org.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import pantryTextual.ui.internal.PantryTextualActivator;

public class PantryTextualUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PantryTextualActivator.getInstance().getInjector("org.example.PantryTextual");
	}

}
