/*
 * generated by Xtext 2.23.0
 */
package org.textual;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RecipeMLRuntimeModule extends AbstractRecipeMLRuntimeModule {
}
