/*
 * generated by Xtext 2.23.0
 */
package org.example.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import pantryTextual.ui.internal.PantryTextualActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PantryTextualExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(PantryTextualActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		PantryTextualActivator activator = PantryTextualActivator.getInstance();
		return activator != null ? activator.getInjector(PantryTextualActivator.ORG_EXAMPLE_PANTRYTEXTUAL) : null;
	}

}
